# Site settings
name: Less Or More
email: zhangzhehui_zzh@163.com
author: Toby Zhang
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/xyztoby
baseurl: ""
description: To be or not to be?
meta_description: 张浙徽;个人博客;好好学习;天天向上;Go head;It's ok
motto: It's our wits that make us men.
banner: 好好学习，天天向上

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xyztoby

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

